import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

type ServiceSeed = {
  serviceType: string;
  name: string;
  description: string;
  icon: string;
  pricePer1000: number;
  minQuantity: number;
  maxQuantity: number;
  speedLabel: string;
  badge?: "Hot" | "Stable" | "Elite";
};

type CategorySeed = {
  name: string;
  icon: string;
  services: ServiceSeed[];
};

const catalog: CategorySeed[] = [
  {
    name: "Instagram",
    icon: "photo_camera",
    services: [
      {
        serviceType: "Followers",
        name: "Instagram Real Followers - HQ",
        description:
          "High quality profiles with organic growth patterns. Minimum drop rate guaranteed with 30-day refill.",
        icon: "group",
        pricePer1000: 1.2,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Instant",
        badge: "Hot",
      },
      {
        serviceType: "Likes",
        name: "Instagram Real Likes",
        description: "Fast, real-looking likes from active profiles. No password required.",
        icon: "favorite",
        pricePer1000: 0.6,
        minQuantity: 50,
        maxQuantity: 100000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Views",
        name: "Instagram Video Views",
        description: "High-speed views for feed videos and IGTV. Safe delivery, no drop.",
        icon: "play_circle",
        pricePer1000: 0.15,
        minQuantity: 100,
        maxQuantity: 1000000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Comments",
        name: "Custom Comments - AI Generated",
        description: "Context-aware comments using advanced AI to match your post content perfectly.",
        icon: "chat",
        pricePer1000: 5.2,
        minQuantity: 10,
        maxQuantity: 1000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Story Views",
        name: "Instagram Story Views",
        description: "Boost story reach with real, active viewer accounts.",
        icon: "auto_stories",
        pricePer1000: 0.8,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Reel Views",
        name: "Instagram Reel Views",
        description: "High-retention Reel views optimized for algorithm reach.",
        icon: "movie",
        pricePer1000: 0.2,
        minQuantity: 100,
        maxQuantity: 1000000,
        speedLabel: "Instant",
        badge: "Elite",
      },
      {
        serviceType: "Saves",
        name: "Instagram Post Saves",
        description: "Improve post ranking signals with real saves.",
        icon: "bookmark",
        pricePer1000: 1.5,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "1 hour start",
      },
      {
        serviceType: "Shares",
        name: "Instagram Post Shares",
        description: "Increase distribution with real profile shares to stories/DMs.",
        icon: "share",
        pricePer1000: 1.0,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "1 hour start",
      },
    ],
  },
  {
    name: "TikTok",
    icon: "music_note",
    services: [
      {
        serviceType: "Followers",
        name: "TikTok Real Followers",
        description: "Organic-looking followers with zero drop history over 90 days.",
        icon: "group",
        pricePer1000: 0.9,
        minQuantity: 100,
        maxQuantity: 100000,
        speedLabel: "Instant",
        badge: "Hot",
      },
      {
        serviceType: "Likes",
        name: "TikTok Real Likes - Instant",
        description: "Boost your TikTok engagement instantly. High-quality accounts.",
        icon: "favorite",
        pricePer1000: 0.85,
        minQuantity: 50,
        maxQuantity: 200000,
        speedLabel: "10m / 1k",
      },
      {
        serviceType: "Views",
        name: "TikTok Video Views",
        description: "Ultra-fast views to help videos hit the For You Page.",
        icon: "visibility",
        pricePer1000: 0.05,
        minQuantity: 100,
        maxQuantity: 5000000,
        speedLabel: "Turbo",
      },
      {
        serviceType: "Comments",
        name: "TikTok Custom Comments",
        description: "Real-looking custom comments written to match your content.",
        icon: "chat",
        pricePer1000: 4.5,
        minQuantity: 10,
        maxQuantity: 1000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Shares",
        name: "TikTok Video Shares - Viral Pack",
        description: "Engineered to trigger the TikTok algorithm for explore page visibility.",
        icon: "share",
        pricePer1000: 0.45,
        minQuantity: 100,
        maxQuantity: 500000,
        speedLabel: "Turbo",
      },
      {
        serviceType: "Saves",
        name: "TikTok Video Saves",
        description: "Real saves to boost content ranking signals.",
        icon: "bookmark",
        pricePer1000: 1.2,
        minQuantity: 50,
        maxQuantity: 50000,
        speedLabel: "1 hour start",
      },
      {
        serviceType: "Live Viewers",
        name: "TikTok Live Stream Viewers",
        description: "Concurrent live viewers to boost visibility during broadcasts.",
        icon: "live_tv",
        pricePer1000: 3.0,
        minQuantity: 50,
        maxQuantity: 5000,
        speedLabel: "Instant",
        badge: "Elite",
      },
    ],
  },
  {
    name: "YouTube",
    icon: "smart_display",
    services: [
      {
        serviceType: "Subscribers",
        name: "YouTube Real Subscribers",
        description: "High-retention subscribers from real accounts, gradual delivery.",
        icon: "person_add",
        pricePer1000: 3.8,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "24 hours start",
      },
      {
        serviceType: "Views",
        name: "YouTube High Retention Views",
        description: "4K Quality, safe for monetization. Average watch time: 5-8 minutes.",
        icon: "smart_display",
        pricePer1000: 3.5,
        minQuantity: 100,
        maxQuantity: 1000000,
        speedLabel: "1k / day",
        badge: "Elite",
      },
      {
        serviceType: "Likes",
        name: "YouTube Video Likes",
        description: "Real-looking likes delivered gradually for a natural pattern.",
        icon: "thumb_up",
        pricePer1000: 1.8,
        minQuantity: 50,
        maxQuantity: 50000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Comments",
        name: "YouTube Custom Comments",
        description: "Relevant, human-written comments for your video content.",
        icon: "chat",
        pricePer1000: 6.0,
        minQuantity: 10,
        maxQuantity: 500,
        speedLabel: "12 hours start",
      },
      {
        serviceType: "Watch Time",
        name: "YouTube Watch Time Hours",
        description: "Real watch-time hours toward monetization requirements.",
        icon: "schedule",
        pricePer1000: 12.0,
        minQuantity: 500,
        maxQuantity: 4000,
        speedLabel: "7-15 days",
        badge: "Stable",
      },
      {
        serviceType: "Shares",
        name: "YouTube Video Shares",
        description: "Social shares to boost external traffic signals.",
        icon: "share",
        pricePer1000: 1.0,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "Instant",
      },
    ],
  },
  {
    name: "Facebook",
    icon: "thumb_up",
    services: [
      {
        serviceType: "Likes",
        name: "Facebook Post Likes",
        description: "Real-looking likes for posts and photos.",
        icon: "thumb_up",
        pricePer1000: 1.1,
        minQuantity: 50,
        maxQuantity: 50000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Followers",
        name: "Facebook Profile Followers",
        description: "Grow your personal profile's follower count.",
        icon: "group",
        pricePer1000: 1.3,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Views",
        name: "Facebook Video Views",
        description: "High-retention video views for feed and Watch.",
        icon: "visibility",
        pricePer1000: 0.2,
        minQuantity: 100,
        maxQuantity: 1000000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Comments",
        name: "Facebook Custom Comments",
        description: "Relevant custom comments for posts and photos.",
        icon: "chat",
        pricePer1000: 5.5,
        minQuantity: 10,
        maxQuantity: 1000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Reactions",
        name: "Facebook Reactions Mix",
        description: "Mixed reactions (Love, Wow, Haha) for authentic engagement.",
        icon: "sentiment_satisfied",
        pricePer1000: 0.9,
        minQuantity: 50,
        maxQuantity: 50000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Reviews",
        name: "Facebook Page Reviews",
        description: "5-star written reviews from real profiles.",
        icon: "star",
        pricePer1000: 8.0,
        minQuantity: 10,
        maxQuantity: 500,
        speedLabel: "24-48 hours",
        badge: "Stable",
      },
      {
        serviceType: "Page Likes",
        name: "Facebook Page Likes",
        description: "Grow your business Page's like count with real profiles.",
        icon: "thumb_up",
        pricePer1000: 1.4,
        minQuantity: 100,
        maxQuantity: 100000,
        speedLabel: "Instant",
        badge: "Hot",
      },
      {
        serviceType: "Post Engagement",
        name: "Facebook Post Engagement Bundle",
        description: "Combined likes, comments and shares package for a single post.",
        icon: "forum",
        pricePer1000: 1.0,
        minQuantity: 100,
        maxQuantity: 20000,
        speedLabel: "1 hour start",
      },
    ],
  },
  {
    name: "Telegram",
    icon: "send",
    services: [
      {
        serviceType: "Channel Members",
        name: "Telegram Channel Members",
        description: "Real, active members added to your channel.",
        icon: "group",
        pricePer1000: 1.5,
        minQuantity: 100,
        maxQuantity: 200000,
        speedLabel: "Instant",
        badge: "Hot",
      },
      {
        serviceType: "Group Members",
        name: "Telegram Group Members",
        description: "Grow group headcount with real accounts.",
        icon: "groups",
        pricePer1000: 1.8,
        minQuantity: 100,
        maxQuantity: 100000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Post Views",
        name: "Telegram Post Views",
        description: "Boost view counts on individual channel posts.",
        icon: "visibility",
        pricePer1000: 0.35,
        minQuantity: 100,
        maxQuantity: 1000000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Reactions",
        name: "Telegram Post Reactions (Emojis)",
        description: "Custom emoji reactions on channel posts.",
        icon: "sentiment_satisfied",
        pricePer1000: 0.7,
        minQuantity: 50,
        maxQuantity: 50000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Comments",
        name: "Telegram Custom Comments",
        description: "Relevant comments on discussion-enabled channel posts.",
        icon: "chat",
        pricePer1000: 4.0,
        minQuantity: 10,
        maxQuantity: 1000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Channel Engagement",
        name: "Telegram Channel Engagement Bundle",
        description: "Combined views + reactions package for new posts automatically.",
        icon: "bolt",
        pricePer1000: 2.5,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Auto, ongoing",
        badge: "Elite",
      },
      {
        serviceType: "Subscribers",
        name: "Telegram Channel Subscribers",
        description: "Alternate delivery source for channel subscriber growth.",
        icon: "person_add",
        pricePer1000: 1.5,
        minQuantity: 100,
        maxQuantity: 200000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Poll Votes",
        name: "Telegram Poll Votes",
        description: "Real votes distributed across your poll options.",
        icon: "poll",
        pricePer1000: 0.9,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "Instant",
      },
    ],
  },
  {
    name: "X / Twitter",
    icon: "tag",
    services: [
      {
        serviceType: "Followers",
        name: "X Real Followers",
        description: "High quality followers with organic growth pattern.",
        icon: "group",
        pricePer1000: 2.0,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Likes",
        name: "X Post Likes",
        description: "Fast likes for posts from active accounts.",
        icon: "favorite",
        pricePer1000: 0.7,
        minQuantity: 50,
        maxQuantity: 100000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Retweets",
        name: "X Global Retweets",
        description: "Retweets from a global pool of active accounts.",
        icon: "repeat",
        pricePer1000: 1.2,
        minQuantity: 50,
        maxQuantity: 50000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Views",
        name: "X Post Views",
        description: "Impression boost for posts and videos.",
        icon: "visibility",
        pricePer1000: 0.1,
        minQuantity: 100,
        maxQuantity: 1000000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Comments",
        name: "X Custom Comments",
        description: "Relevant custom replies for posts.",
        icon: "chat",
        pricePer1000: 5.0,
        minQuantity: 10,
        maxQuantity: 1000,
        speedLabel: "Instant",
      },
    ],
  },
  {
    name: "WhatsApp",
    icon: "chat",
    services: [
      {
        serviceType: "Group Members",
        name: "WhatsApp Group Members",
        description: "Grow your group with real active numbers.",
        icon: "groups",
        pricePer1000: 2.5,
        minQuantity: 50,
        maxQuantity: 10000,
        speedLabel: "24-48 hours",
      },
      {
        serviceType: "Status Views",
        name: "WhatsApp Status Views",
        description: "Boost views on your WhatsApp status updates.",
        icon: "visibility",
        pricePer1000: 1.0,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Status Reactions",
        name: "WhatsApp Status Reactions",
        description: "Real emoji reactions on status updates.",
        icon: "sentiment_satisfied",
        pricePer1000: 1.2,
        minQuantity: 50,
        maxQuantity: 10000,
        speedLabel: "Instant",
      },
    ],
  },
  {
    name: "Snapchat",
    icon: "camera_alt",
    services: [
      {
        serviceType: "Followers",
        name: "Snapchat Followers",
        description: "Real followers added gradually for a natural pattern.",
        icon: "group",
        pricePer1000: 2.2,
        minQuantity: 100,
        maxQuantity: 20000,
        speedLabel: "24 hours start",
      },
      {
        serviceType: "Story Views",
        name: "Snapchat Story Views",
        description: "Boost story view counts from active accounts.",
        icon: "auto_stories",
        pricePer1000: 0.6,
        minQuantity: 100,
        maxQuantity: 100000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Score Boost",
        name: "Snapchat Score Boost",
        description: "Increase your Snapchat Score through engagement activity.",
        icon: "trending_up",
        pricePer1000: 3.0,
        minQuantity: 1000,
        maxQuantity: 100000,
        speedLabel: "1-3 days",
      },
    ],
  },
  {
    name: "Discord",
    icon: "forum",
    services: [
      {
        serviceType: "Server Members",
        name: "Discord Server Members",
        description: "Grow your server's member count with real accounts.",
        icon: "groups",
        pricePer1000: 2.8,
        minQuantity: 50,
        maxQuantity: 50000,
        speedLabel: "Instant",
        badge: "Hot",
      },
      {
        serviceType: "Online Presence",
        name: "Discord Online Members Boost",
        description: "Boost concurrent online member count for social proof.",
        icon: "person",
        pricePer1000: 3.5,
        minQuantity: 50,
        maxQuantity: 10000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Message Reactions",
        name: "Discord Message Reactions",
        description: "Real emoji reactions on server messages.",
        icon: "sentiment_satisfied",
        pricePer1000: 0.8,
        minQuantity: 20,
        maxQuantity: 5000,
        speedLabel: "Instant",
      },
    ],
  },
  {
    name: "Spotify",
    icon: "graphic_eq",
    services: [
      {
        serviceType: "Streams",
        name: "Spotify Track Streams",
        description: "Real streams from active listener accounts, royalty-safe delivery.",
        icon: "graphic_eq",
        pricePer1000: 4.5,
        minQuantity: 1000,
        maxQuantity: 1000000,
        speedLabel: "Gradual, 5-7 days",
        badge: "Stable",
      },
      {
        serviceType: "Followers",
        name: "Spotify Profile Followers",
        description: "Grow your artist or profile follower count.",
        icon: "group",
        pricePer1000: 2.0,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Playlist Followers",
        name: "Spotify Playlist Followers",
        description: "Real followers added to a specific playlist.",
        icon: "queue_music",
        pricePer1000: 2.3,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Instant",
      },
      {
        serviceType: "Monthly Listeners",
        name: "Spotify Monthly Listeners Boost",
        description: "Increase your monthly listener count through real plays.",
        icon: "headphones",
        pricePer1000: 5.0,
        minQuantity: 1000,
        maxQuantity: 500000,
        speedLabel: "Gradual, 7-10 days",
        badge: "Elite",
      },
    ],
  },
];

async function main() {
  for (const [index, category] of catalog.entries()) {
    const savedCategory = await prisma.serviceCategory.upsert({
      where: { name: category.name },
      update: { icon: category.icon, sortOrder: index },
      create: { name: category.name, icon: category.icon, sortOrder: index },
    });

    for (const service of category.services) {
      await prisma.service.upsert({
        where: {
          // No natural unique key beyond id, so key on name (unique enough
          // for a seed script — the real catalog will come from a supplier
          // API per PLANO.md section 6).
          id: `${savedCategory.id}-${service.serviceType}-${service.name}`
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, "-"),
        },
        update: {
          ...service,
          categoryId: savedCategory.id,
        },
        create: {
          id: `${savedCategory.id}-${service.serviceType}-${service.name}`
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, "-"),
          categoryId: savedCategory.id,
          ...service,
        },
      });
    }

    console.log(`Seeded ${category.services.length} services for ${category.name}`);
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
