import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

type ServiceSeed = {
  serviceType: string;
  name: string;
  description: string;
  icon: string;
  pricePer1000: number;
  minQuantity: number;
  maxQuantity: number;
  speedLabel: string;
  badge?: "Hot" | "Stable" | "Elite";
  /// Out of 10. Refill-guaranteed "real" services score highest; cheap
  /// bulk/bot-driven ones score lowest — kept honest rather than inflated.
  qualityScore: number;
  /// 0-100.
  retentionPercent: number;
  /// Refill guarantees only make sense for services that can genuinely
  /// "drop" over time (followers/members/subscribers) — matches how real
  /// SMM panels scope refill, not applied to one-time actions like likes,
  /// views, or comments.
  refillDays: number;
};

type CategorySeed = {
  name: string;
  icon: string;
  services: ServiceSeed[];
};

const catalog: CategorySeed[] = [
  {
    name: "Instagram",
    icon: "photo_camera",
    services: [
      {
        serviceType: "Followers",
        name: "Instagram Real Followers - HQ",
        description:
          "High quality profiles with organic growth patterns. Minimum drop rate guaranteed with 30-day refill.",
        icon: "group",
        pricePer1000: 1.2,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Instant",
        badge: "Hot",
        qualityScore: 9.3,
        retentionPercent: 92,
        refillDays: 30,
      },
      {
        serviceType: "Followers",
        name: "Instagram Followers - USA Targeted",
        description: "Premium followers from real US-based accounts. Ideal for local businesses and creators.",
        icon: "flag",
        pricePer1000: 3.5,
        minQuantity: 100,
        maxQuantity: 20000,
        speedLabel: "24 hours start",
        badge: "Elite",
        qualityScore: 9.6,
        retentionPercent: 95,
        refillDays: 60,
      },
      {
        serviceType: "Likes",
        name: "Instagram Real Likes",
        description: "Fast, real-looking likes from active profiles. No password required.",
        icon: "favorite",
        pricePer1000: 0.6,
        minQuantity: 50,
        maxQuantity: 100000,
        speedLabel: "Instant",
        qualityScore: 8.4,
        retentionPercent: 85,
        refillDays: 0,
      },
      {
        serviceType: "Views",
        name: "Instagram Video Views",
        description: "High-speed views for feed videos and IGTV. Safe delivery, no drop.",
        icon: "play_circle",
        pricePer1000: 0.15,
        minQuantity: 100,
        maxQuantity: 1000000,
        speedLabel: "Instant",
        qualityScore: 7.8,
        retentionPercent: 80,
        refillDays: 0,
      },
      {
        serviceType: "Comments",
        name: "Custom Comments - AI Generated",
        description: "Context-aware comments using advanced AI to match your post content perfectly.",
        icon: "chat",
        pricePer1000: 5.2,
        minQuantity: 10,
        maxQuantity: 1000,
        speedLabel: "Instant",
        qualityScore: 9.1,
        retentionPercent: 96,
        refillDays: 0,
      },
      {
        serviceType: "Story Views",
        name: "Instagram Story Views",
        description: "Boost story reach with real, active viewer accounts.",
        icon: "auto_stories",
        pricePer1000: 0.8,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Instant",
        qualityScore: 8.0,
        retentionPercent: 82,
        refillDays: 0,
      },
      {
        serviceType: "Reel Views",
        name: "Instagram Reel Views",
        description: "High-retention Reel views optimized for algorithm reach.",
        icon: "movie",
        pricePer1000: 0.2,
        minQuantity: 100,
        maxQuantity: 1000000,
        speedLabel: "Instant",
        badge: "Elite",
        qualityScore: 9.0,
        retentionPercent: 88,
        refillDays: 0,
      },
      {
        serviceType: "Saves",
        name: "Instagram Post Saves",
        description: "Improve post ranking signals with real saves.",
        icon: "bookmark",
        pricePer1000: 1.5,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "1 hour start",
        qualityScore: 8.6,
        retentionPercent: 88,
        refillDays: 0,
      },
      {
        serviceType: "Shares",
        name: "Instagram Post Shares",
        description: "Increase distribution with real profile shares to stories/DMs.",
        icon: "share",
        pricePer1000: 1.0,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "1 hour start",
        qualityScore: 8.3,
        retentionPercent: 83,
        refillDays: 0,
      },
      {
        serviceType: "Auto Engagement",
        name: "Instagram Auto-Likes Subscription",
        description: "Automatically delivers likes to every new post you publish — set it and forget it.",
        icon: "autorenew",
        pricePer1000: 0.75,
        minQuantity: 500,
        maxQuantity: 50000,
        speedLabel: "Auto, ongoing",
        badge: "Elite",
        qualityScore: 8.9,
        retentionPercent: 87,
        refillDays: 0,
      },
      {
        serviceType: "Live Viewers",
        name: "Instagram Live Stream Viewers",
        description: "Concurrent viewers for Instagram Live broadcasts to boost social proof.",
        icon: "live_tv",
        pricePer1000: 3.2,
        minQuantity: 50,
        maxQuantity: 5000,
        speedLabel: "Instant",
        qualityScore: 8.2,
        retentionPercent: 78,
        refillDays: 0,
      },
    ],
  },
  {
    name: "TikTok",
    icon: "music_note",
    services: [
      {
        serviceType: "Followers",
        name: "TikTok Real Followers",
        description: "Organic-looking followers with zero drop history over 90 days.",
        icon: "group",
        pricePer1000: 0.9,
        minQuantity: 100,
        maxQuantity: 100000,
        speedLabel: "Instant",
        badge: "Hot",
        qualityScore: 9.2,
        retentionPercent: 91,
        refillDays: 30,
      },
      {
        serviceType: "Followers",
        name: "TikTok Followers - Niche Targeted",
        description: "Followers filtered by interest niche for higher engagement rates.",
        icon: "target",
        pricePer1000: 2.4,
        minQuantity: 100,
        maxQuantity: 30000,
        speedLabel: "24 hours start",
        badge: "Elite",
        qualityScore: 9.4,
        retentionPercent: 93,
        refillDays: 30,
      },
      {
        serviceType: "Likes",
        name: "TikTok Real Likes - Instant",
        description: "Boost your TikTok engagement instantly. High-quality accounts.",
        icon: "favorite",
        pricePer1000: 0.85,
        minQuantity: 50,
        maxQuantity: 200000,
        speedLabel: "10m / 1k",
        qualityScore: 8.3,
        retentionPercent: 84,
        refillDays: 0,
      },
      {
        serviceType: "Views",
        name: "TikTok Video Views",
        description: "Ultra-fast views to help videos hit the For You Page.",
        icon: "visibility",
        pricePer1000: 0.05,
        minQuantity: 100,
        maxQuantity: 5000000,
        speedLabel: "Turbo",
        qualityScore: 7.5,
        retentionPercent: 75,
        refillDays: 0,
      },
      {
        serviceType: "Comments",
        name: "TikTok Custom Comments",
        description: "Real-looking custom comments written to match your content.",
        icon: "chat",
        pricePer1000: 4.5,
        minQuantity: 10,
        maxQuantity: 1000,
        speedLabel: "Instant",
        qualityScore: 9.0,
        retentionPercent: 95,
        refillDays: 0,
      },
      {
        serviceType: "Shares",
        name: "TikTok Video Shares - Viral Pack",
        description: "Engineered to trigger the TikTok algorithm for explore page visibility.",
        icon: "share",
        pricePer1000: 0.45,
        minQuantity: 100,
        maxQuantity: 500000,
        speedLabel: "Turbo",
        qualityScore: 8.1,
        retentionPercent: 80,
        refillDays: 0,
      },
      {
        serviceType: "Saves",
        name: "TikTok Video Saves",
        description: "Real saves to boost content ranking signals.",
        icon: "bookmark",
        pricePer1000: 1.2,
        minQuantity: 50,
        maxQuantity: 50000,
        speedLabel: "1 hour start",
        qualityScore: 8.5,
        retentionPercent: 86,
        refillDays: 0,
      },
      {
        serviceType: "Live Viewers",
        name: "TikTok Live Stream Viewers",
        description: "Concurrent live viewers to boost visibility during broadcasts.",
        icon: "live_tv",
        pricePer1000: 3.0,
        minQuantity: 50,
        maxQuantity: 5000,
        speedLabel: "Instant",
        badge: "Elite",
        qualityScore: 8.4,
        retentionPercent: 79,
        refillDays: 0,
      },
      {
        serviceType: "Auto Engagement",
        name: "TikTok Auto-Likes Subscription",
        description: "Automatically delivers likes to every new video you post.",
        icon: "autorenew",
        pricePer1000: 0.7,
        minQuantity: 500,
        maxQuantity: 100000,
        speedLabel: "Auto, ongoing",
        badge: "Elite",
        qualityScore: 8.7,
        retentionPercent: 85,
        refillDays: 0,
      },
    ],
  },
  {
    name: "YouTube",
    icon: "smart_display",
    services: [
      {
        serviceType: "Subscribers",
        name: "YouTube Real Subscribers",
        description: "High-retention subscribers from real accounts, gradual delivery.",
        icon: "person_add",
        pricePer1000: 3.8,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "24 hours start",
        qualityScore: 9.1,
        retentionPercent: 90,
        refillDays: 30,
      },
      {
        serviceType: "Views",
        name: "YouTube High Retention Views",
        description: "4K Quality, safe for monetization. Average watch time: 5-8 minutes.",
        icon: "smart_display",
        pricePer1000: 3.5,
        minQuantity: 100,
        maxQuantity: 1000000,
        speedLabel: "1k / day",
        badge: "Elite",
        qualityScore: 9.5,
        retentionPercent: 93,
        refillDays: 0,
      },
      {
        serviceType: "Views",
        name: "YouTube Shorts Views",
        description: "Fast views optimized for the Shorts feed algorithm.",
        icon: "smartphone",
        pricePer1000: 0.4,
        minQuantity: 100,
        maxQuantity: 1000000,
        speedLabel: "Turbo",
        qualityScore: 8.0,
        retentionPercent: 78,
        refillDays: 0,
      },
      {
        serviceType: "Likes",
        name: "YouTube Video Likes",
        description: "Real-looking likes delivered gradually for a natural pattern.",
        icon: "thumb_up",
        pricePer1000: 1.8,
        minQuantity: 50,
        maxQuantity: 50000,
        speedLabel: "Instant",
        qualityScore: 8.5,
        retentionPercent: 87,
        refillDays: 0,
      },
      {
        serviceType: "Comments",
        name: "YouTube Custom Comments",
        description: "Relevant, human-written comments for your video content.",
        icon: "chat",
        pricePer1000: 6.0,
        minQuantity: 10,
        maxQuantity: 500,
        speedLabel: "12 hours start",
        qualityScore: 9.2,
        retentionPercent: 96,
        refillDays: 0,
      },
      {
        serviceType: "Watch Time",
        name: "YouTube Watch Time Hours",
        description: "Real watch-time hours toward monetization requirements.",
        icon: "schedule",
        pricePer1000: 12.0,
        minQuantity: 500,
        maxQuantity: 4000,
        speedLabel: "7-15 days",
        badge: "Stable",
        qualityScore: 9.4,
        retentionPercent: 92,
        refillDays: 0,
      },
      {
        serviceType: "Shares",
        name: "YouTube Video Shares",
        description: "Social shares to boost external traffic signals.",
        icon: "share",
        pricePer1000: 1.0,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "Instant",
        qualityScore: 8.0,
        retentionPercent: 81,
        refillDays: 0,
      },
      {
        serviceType: "Community",
        name: "YouTube Community Post Likes",
        description: "Likes for Community tab posts, polls, and images.",
        icon: "forum",
        pricePer1000: 2.0,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "Instant",
        qualityScore: 8.2,
        retentionPercent: 84,
        refillDays: 0,
      },
      {
        serviceType: "Live Viewers",
        name: "YouTube Live Stream Viewers",
        description: "Concurrent live viewers to boost stream ranking and social proof.",
        icon: "live_tv",
        pricePer1000: 5.5,
        minQuantity: 50,
        maxQuantity: 5000,
        speedLabel: "Instant",
        badge: "Elite",
        qualityScore: 8.6,
        retentionPercent: 80,
        refillDays: 0,
      },
    ],
  },
  {
    name: "Facebook",
    icon: "thumb_up",
    services: [
      {
        serviceType: "Likes",
        name: "Facebook Post Likes",
        description: "Real-looking likes for posts and photos.",
        icon: "thumb_up",
        pricePer1000: 1.1,
        minQuantity: 50,
        maxQuantity: 50000,
        speedLabel: "Instant",
        qualityScore: 8.2,
        retentionPercent: 83,
        refillDays: 0,
      },
      {
        serviceType: "Followers",
        name: "Facebook Profile Followers",
        description: "Grow your personal profile's follower count.",
        icon: "group",
        pricePer1000: 1.3,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Instant",
        qualityScore: 8.4,
        retentionPercent: 85,
        refillDays: 30,
      },
      {
        serviceType: "Views",
        name: "Facebook Video Views",
        description: "High-retention video views for feed and Watch.",
        icon: "visibility",
        pricePer1000: 0.2,
        minQuantity: 100,
        maxQuantity: 1000000,
        speedLabel: "Instant",
        qualityScore: 7.7,
        retentionPercent: 77,
        refillDays: 0,
      },
      {
        serviceType: "Comments",
        name: "Facebook Custom Comments",
        description: "Relevant custom comments for posts and photos.",
        icon: "chat",
        pricePer1000: 5.5,
        minQuantity: 10,
        maxQuantity: 1000,
        speedLabel: "Instant",
        qualityScore: 9.0,
        retentionPercent: 95,
        refillDays: 0,
      },
      {
        serviceType: "Reactions",
        name: "Facebook Reactions Mix",
        description: "Mixed reactions (Love, Wow, Haha) for authentic engagement.",
        icon: "sentiment_satisfied",
        pricePer1000: 0.9,
        minQuantity: 50,
        maxQuantity: 50000,
        speedLabel: "Instant",
        qualityScore: 8.1,
        retentionPercent: 82,
        refillDays: 0,
      },
      {
        serviceType: "Reviews",
        name: "Facebook Page Reviews",
        description: "5-star written reviews from real profiles.",
        icon: "star",
        pricePer1000: 8.0,
        minQuantity: 10,
        maxQuantity: 500,
        speedLabel: "24-48 hours",
        badge: "Stable",
        qualityScore: 9.3,
        retentionPercent: 94,
        refillDays: 0,
      },
      {
        serviceType: "Page Likes",
        name: "Facebook Page Likes",
        description: "Grow your business Page's like count with real profiles.",
        icon: "thumb_up",
        pricePer1000: 1.4,
        minQuantity: 100,
        maxQuantity: 100000,
        speedLabel: "Instant",
        badge: "Hot",
        qualityScore: 8.8,
        retentionPercent: 88,
        refillDays: 30,
      },
      {
        serviceType: "Post Engagement",
        name: "Facebook Post Engagement Bundle",
        description: "Combined likes, comments and shares package for a single post.",
        icon: "forum",
        pricePer1000: 1.0,
        minQuantity: 100,
        maxQuantity: 20000,
        speedLabel: "1 hour start",
        qualityScore: 8.3,
        retentionPercent: 84,
        refillDays: 0,
      },
      {
        serviceType: "Group Members",
        name: "Facebook Group Members",
        description: "Grow your Facebook Group's member count with real profiles.",
        icon: "groups",
        pricePer1000: 1.9,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "24 hours start",
        qualityScore: 8.5,
        retentionPercent: 86,
        refillDays: 30,
      },
      {
        serviceType: "Event Responses",
        name: "Facebook Event Responses",
        description: "'Going' and 'Interested' responses to boost event visibility.",
        icon: "event",
        pricePer1000: 2.2,
        minQuantity: 50,
        maxQuantity: 10000,
        speedLabel: "Instant",
        qualityScore: 8.0,
        retentionPercent: 80,
        refillDays: 0,
      },
    ],
  },
  {
    name: "Telegram",
    icon: "send",
    services: [
      {
        serviceType: "Channel Members",
        name: "Telegram Channel Members",
        description: "Real, active members added to your channel.",
        icon: "group",
        pricePer1000: 1.5,
        minQuantity: 100,
        maxQuantity: 200000,
        speedLabel: "Instant",
        badge: "Hot",
        qualityScore: 9.1,
        retentionPercent: 90,
        refillDays: 30,
      },
      {
        serviceType: "Channel Members",
        name: "Telegram Channel Members - Premium Targeted",
        description: "Country/niche-targeted members for higher genuine engagement.",
        icon: "flag",
        pricePer1000: 4.0,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "24 hours start",
        badge: "Elite",
        qualityScore: 9.6,
        retentionPercent: 95,
        refillDays: 60,
      },
      {
        serviceType: "Group Members",
        name: "Telegram Group Members",
        description: "Grow group headcount with real accounts.",
        icon: "groups",
        pricePer1000: 1.8,
        minQuantity: 100,
        maxQuantity: 100000,
        speedLabel: "Instant",
        qualityScore: 8.8,
        retentionPercent: 87,
        refillDays: 30,
      },
      {
        serviceType: "Post Views",
        name: "Telegram Post Views",
        description: "Boost view counts on individual channel posts.",
        icon: "visibility",
        pricePer1000: 0.35,
        minQuantity: 100,
        maxQuantity: 1000000,
        speedLabel: "Instant",
        qualityScore: 8.0,
        retentionPercent: 81,
        refillDays: 0,
      },
      {
        serviceType: "Post Views",
        name: "Telegram Auto Views Subscription",
        description: "Automatically delivers views to every new post published in your channel.",
        icon: "autorenew",
        pricePer1000: 0.3,
        minQuantity: 1000,
        maxQuantity: 500000,
        speedLabel: "Auto, ongoing",
        badge: "Elite",
        qualityScore: 8.7,
        retentionPercent: 85,
        refillDays: 0,
      },
      {
        serviceType: "Reactions",
        name: "Telegram Post Reactions (Emojis)",
        description: "Custom emoji reactions on channel posts.",
        icon: "sentiment_satisfied",
        pricePer1000: 0.7,
        minQuantity: 50,
        maxQuantity: 50000,
        speedLabel: "Instant",
        qualityScore: 8.3,
        retentionPercent: 84,
        refillDays: 0,
      },
      {
        serviceType: "Reactions",
        name: "Telegram Premium Reactions",
        description: "Paid/premium emoji reactions for a more authentic, high-value look.",
        icon: "workspace_premium",
        pricePer1000: 1.6,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "Instant",
        badge: "Elite",
        qualityScore: 9.0,
        retentionPercent: 89,
        refillDays: 0,
      },
      {
        serviceType: "Comments",
        name: "Telegram Custom Comments",
        description: "Relevant comments on discussion-enabled channel posts.",
        icon: "chat",
        pricePer1000: 4.0,
        minQuantity: 10,
        maxQuantity: 1000,
        speedLabel: "Instant",
        qualityScore: 9.0,
        retentionPercent: 95,
        refillDays: 0,
      },
      {
        serviceType: "Channel Engagement",
        name: "Telegram Channel Engagement Bundle",
        description: "Combined views + reactions package for new posts automatically.",
        icon: "bolt",
        pricePer1000: 2.5,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Auto, ongoing",
        badge: "Elite",
        qualityScore: 9.2,
        retentionPercent: 90,
        refillDays: 0,
      },
      {
        serviceType: "Subscribers",
        name: "Telegram Channel Subscribers",
        description: "Alternate delivery source for channel subscriber growth.",
        icon: "person_add",
        pricePer1000: 1.5,
        minQuantity: 100,
        maxQuantity: 200000,
        speedLabel: "Instant",
        qualityScore: 8.6,
        retentionPercent: 86,
        refillDays: 30,
      },
      {
        serviceType: "Poll Votes",
        name: "Telegram Poll Votes",
        description: "Real votes distributed across your poll options.",
        icon: "poll",
        pricePer1000: 0.9,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "Instant",
        qualityScore: 8.1,
        retentionPercent: 82,
        refillDays: 0,
      },
      {
        serviceType: "Story Views",
        name: "Telegram Story Views",
        description: "Views for Telegram Stories to boost visibility on your profile.",
        icon: "auto_stories",
        pricePer1000: 0.6,
        minQuantity: 100,
        maxQuantity: 100000,
        speedLabel: "Instant",
        qualityScore: 7.9,
        retentionPercent: 79,
        refillDays: 0,
      },
      {
        serviceType: "Channel Boosts",
        name: "Telegram Channel Boosts",
        description: "Real Telegram Boosts to raise your channel's level and unlock perks.",
        icon: "rocket_launch",
        pricePer1000: 18.0,
        minQuantity: 10,
        maxQuantity: 500,
        speedLabel: "1-3 days",
        badge: "Elite",
        qualityScore: 9.5,
        retentionPercent: 93,
        refillDays: 0,
      },
      {
        serviceType: "Post Forwards",
        name: "Telegram Post Forwards",
        description: "Increase distribution by forwarding your post to real user chats.",
        icon: "forward",
        pricePer1000: 1.3,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "Instant",
        qualityScore: 8.2,
        retentionPercent: 83,
        refillDays: 0,
      },
      {
        serviceType: "Bot Subscribers",
        name: "Telegram Bot Start/Subscribers",
        description: "Real users who start your bot — built for bot developers growing an audience.",
        icon: "smart_toy",
        pricePer1000: 2.8,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "24 hours start",
        badge: "Stable",
        qualityScore: 8.7,
        retentionPercent: 85,
        refillDays: 15,
      },
    ],
  },
  {
    name: "X / Twitter",
    icon: "tag",
    services: [
      {
        serviceType: "Followers",
        name: "X Real Followers",
        description: "High quality followers with organic growth pattern.",
        icon: "group",
        pricePer1000: 2.0,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Instant",
        qualityScore: 8.9,
        retentionPercent: 89,
        refillDays: 30,
      },
      {
        serviceType: "Likes",
        name: "X Post Likes",
        description: "Fast likes for posts from active accounts.",
        icon: "favorite",
        pricePer1000: 0.7,
        minQuantity: 50,
        maxQuantity: 100000,
        speedLabel: "Instant",
        qualityScore: 8.0,
        retentionPercent: 80,
        refillDays: 0,
      },
      {
        serviceType: "Retweets",
        name: "X Global Retweets",
        description: "Retweets from a global pool of active accounts.",
        icon: "repeat",
        pricePer1000: 1.2,
        minQuantity: 50,
        maxQuantity: 50000,
        speedLabel: "Instant",
        qualityScore: 8.2,
        retentionPercent: 82,
        refillDays: 0,
      },
      {
        serviceType: "Views",
        name: "X Post Views",
        description: "Impression boost for posts and videos.",
        icon: "visibility",
        pricePer1000: 0.1,
        minQuantity: 100,
        maxQuantity: 1000000,
        speedLabel: "Instant",
        qualityScore: 7.4,
        retentionPercent: 74,
        refillDays: 0,
      },
      {
        serviceType: "Comments",
        name: "X Custom Comments",
        description: "Relevant custom replies for posts.",
        icon: "chat",
        pricePer1000: 5.0,
        minQuantity: 10,
        maxQuantity: 1000,
        speedLabel: "Instant",
        qualityScore: 8.9,
        retentionPercent: 94,
        refillDays: 0,
      },
      {
        serviceType: "Bookmarks",
        name: "X Post Bookmarks",
        description: "Real bookmarks/saves to boost the algorithm's quality signal.",
        icon: "bookmark",
        pricePer1000: 1.4,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "Instant",
        qualityScore: 8.3,
        retentionPercent: 84,
        refillDays: 0,
      },
      {
        serviceType: "Spaces Listeners",
        name: "X Spaces Listeners",
        description: "Concurrent listeners for live X Spaces audio rooms.",
        icon: "podcasts",
        pricePer1000: 4.5,
        minQuantity: 20,
        maxQuantity: 2000,
        speedLabel: "Instant",
        badge: "Elite",
        qualityScore: 8.5,
        retentionPercent: 78,
        refillDays: 0,
      },
    ],
  },
  {
    name: "WhatsApp",
    icon: "chat",
    services: [
      {
        serviceType: "Group Members",
        name: "WhatsApp Group Members",
        description: "Grow your group with real active numbers.",
        icon: "groups",
        pricePer1000: 2.5,
        minQuantity: 50,
        maxQuantity: 10000,
        speedLabel: "24-48 hours",
        qualityScore: 8.3,
        retentionPercent: 82,
        refillDays: 15,
      },
      {
        serviceType: "Status Views",
        name: "WhatsApp Status Views",
        description: "Boost views on your WhatsApp status updates.",
        icon: "visibility",
        pricePer1000: 1.0,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "Instant",
        qualityScore: 7.9,
        retentionPercent: 79,
        refillDays: 0,
      },
      {
        serviceType: "Status Reactions",
        name: "WhatsApp Status Reactions",
        description: "Real emoji reactions on status updates.",
        icon: "sentiment_satisfied",
        pricePer1000: 1.2,
        minQuantity: 50,
        maxQuantity: 10000,
        speedLabel: "Instant",
        qualityScore: 8.0,
        retentionPercent: 80,
        refillDays: 0,
      },
      {
        serviceType: "Channel Followers",
        name: "WhatsApp Channel Followers",
        description: "Grow your WhatsApp Channel's follower count with real numbers.",
        icon: "campaign",
        pricePer1000: 2.8,
        minQuantity: 100,
        maxQuantity: 30000,
        speedLabel: "24 hours start",
        badge: "Hot",
        qualityScore: 8.6,
        retentionPercent: 85,
        refillDays: 30,
      },
    ],
  },
  {
    name: "Snapchat",
    icon: "camera_alt",
    services: [
      {
        serviceType: "Followers",
        name: "Snapchat Followers",
        description: "Real followers added gradually for a natural pattern.",
        icon: "group",
        pricePer1000: 2.2,
        minQuantity: 100,
        maxQuantity: 20000,
        speedLabel: "24 hours start",
        qualityScore: 8.4,
        retentionPercent: 84,
        refillDays: 30,
      },
      {
        serviceType: "Story Views",
        name: "Snapchat Story Views",
        description: "Boost story view counts from active accounts.",
        icon: "auto_stories",
        pricePer1000: 0.6,
        minQuantity: 100,
        maxQuantity: 100000,
        speedLabel: "Instant",
        qualityScore: 7.8,
        retentionPercent: 78,
        refillDays: 0,
      },
      {
        serviceType: "Score Boost",
        name: "Snapchat Score Boost",
        description: "Increase your Snapchat Score through engagement activity.",
        icon: "trending_up",
        pricePer1000: 3.0,
        minQuantity: 1000,
        maxQuantity: 100000,
        speedLabel: "1-3 days",
        qualityScore: 7.6,
        retentionPercent: 76,
        refillDays: 0,
      },
      {
        serviceType: "Spotlight Views",
        name: "Snapchat Spotlight Views",
        description: "Views for Spotlight submissions to boost discoverability.",
        icon: "star",
        pricePer1000: 0.5,
        minQuantity: 500,
        maxQuantity: 500000,
        speedLabel: "Instant",
        qualityScore: 7.7,
        retentionPercent: 77,
        refillDays: 0,
      },
    ],
  },
  {
    name: "Discord",
    icon: "forum",
    services: [
      {
        serviceType: "Server Members",
        name: "Discord Server Members",
        description: "Grow your server's member count with real accounts.",
        icon: "groups",
        pricePer1000: 2.8,
        minQuantity: 50,
        maxQuantity: 50000,
        speedLabel: "Instant",
        badge: "Hot",
        qualityScore: 8.7,
        retentionPercent: 86,
        refillDays: 30,
      },
      {
        serviceType: "Online Presence",
        name: "Discord Online Members Boost",
        description: "Boost concurrent online member count for social proof.",
        icon: "person",
        pricePer1000: 3.5,
        minQuantity: 50,
        maxQuantity: 10000,
        speedLabel: "Instant",
        qualityScore: 7.9,
        retentionPercent: 75,
        refillDays: 0,
      },
      {
        serviceType: "Message Reactions",
        name: "Discord Message Reactions",
        description: "Real emoji reactions on server messages.",
        icon: "sentiment_satisfied",
        pricePer1000: 0.8,
        minQuantity: 20,
        maxQuantity: 5000,
        speedLabel: "Instant",
        qualityScore: 8.1,
        retentionPercent: 81,
        refillDays: 0,
      },
      {
        serviceType: "Server Boosts",
        name: "Discord Server Boosts",
        description: "Real Nitro Boosts to level up your server and unlock perks.",
        icon: "rocket_launch",
        pricePer1000: 22.0,
        minQuantity: 5,
        maxQuantity: 200,
        speedLabel: "1-2 days",
        badge: "Elite",
        qualityScore: 9.4,
        retentionPercent: 92,
        refillDays: 0,
      },
      {
        serviceType: "Voice Channel",
        name: "Discord Voice Channel Members",
        description: "Live voice channel presence to make your server look active.",
        icon: "mic",
        pricePer1000: 6.0,
        minQuantity: 10,
        maxQuantity: 500,
        speedLabel: "Instant",
        qualityScore: 8.0,
        retentionPercent: 76,
        refillDays: 0,
      },
    ],
  },
  {
    name: "Spotify",
    icon: "graphic_eq",
    services: [
      {
        serviceType: "Streams",
        name: "Spotify Track Streams",
        description: "Real streams from active listener accounts, royalty-safe delivery.",
        icon: "graphic_eq",
        pricePer1000: 4.5,
        minQuantity: 1000,
        maxQuantity: 1000000,
        speedLabel: "Gradual, 5-7 days",
        badge: "Stable",
        qualityScore: 9.0,
        retentionPercent: 90,
        refillDays: 0,
      },
      {
        serviceType: "Followers",
        name: "Spotify Profile Followers",
        description: "Grow your artist or profile follower count.",
        icon: "group",
        pricePer1000: 2.0,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Instant",
        qualityScore: 8.4,
        retentionPercent: 85,
        refillDays: 30,
      },
      {
        serviceType: "Playlist Followers",
        name: "Spotify Playlist Followers",
        description: "Real followers added to a specific playlist.",
        icon: "queue_music",
        pricePer1000: 2.3,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Instant",
        qualityScore: 8.3,
        retentionPercent: 84,
        refillDays: 30,
      },
      {
        serviceType: "Monthly Listeners",
        name: "Spotify Monthly Listeners Boost",
        description: "Increase your monthly listener count through real plays.",
        icon: "headphones",
        pricePer1000: 5.0,
        minQuantity: 1000,
        maxQuantity: 500000,
        speedLabel: "Gradual, 7-10 days",
        badge: "Elite",
        qualityScore: 9.2,
        retentionPercent: 91,
        refillDays: 0,
      },
      {
        serviceType: "Saves",
        name: "Spotify Track Saves",
        description: "Real saves to listener libraries — a strong algorithmic quality signal.",
        icon: "bookmark",
        pricePer1000: 3.0,
        minQuantity: 100,
        maxQuantity: 100000,
        speedLabel: "Gradual, 3-5 days",
        qualityScore: 8.8,
        retentionPercent: 89,
        refillDays: 0,
      },
      {
        serviceType: "Playlist Placement",
        name: "Spotify Playlist Placement",
        description: "Curated placement on genre-matched independent playlists for organic discovery.",
        icon: "playlist_add_check",
        pricePer1000: 45.0,
        minQuantity: 1,
        maxQuantity: 10,
        speedLabel: "3-7 days",
        badge: "Elite",
        qualityScore: 9.6,
        retentionPercent: 90,
        refillDays: 0,
      },
    ],
  },
  {
    name: "Threads",
    icon: "alternate_email",
    services: [
      {
        serviceType: "Followers",
        name: "Threads Real Followers",
        description: "Grow your Threads audience with real, active profiles.",
        icon: "group",
        pricePer1000: 2.5,
        minQuantity: 100,
        maxQuantity: 50000,
        speedLabel: "Instant",
        badge: "Hot",
        qualityScore: 8.9,
        retentionPercent: 88,
        refillDays: 30,
      },
      {
        serviceType: "Likes",
        name: "Threads Post Likes",
        description: "Fast likes to boost engagement on your Threads posts.",
        icon: "favorite",
        pricePer1000: 1.0,
        minQuantity: 50,
        maxQuantity: 100000,
        speedLabel: "Instant",
        qualityScore: 8.1,
        retentionPercent: 81,
        refillDays: 0,
      },
      {
        serviceType: "Replies",
        name: "Threads Custom Replies",
        description: "Relevant custom replies to boost conversation and reach.",
        icon: "chat",
        pricePer1000: 5.5,
        minQuantity: 10,
        maxQuantity: 1000,
        speedLabel: "Instant",
        qualityScore: 9.0,
        retentionPercent: 95,
        refillDays: 0,
      },
      {
        serviceType: "Reposts",
        name: "Threads Reposts",
        description: "Reposts from active accounts to boost distribution.",
        icon: "repeat",
        pricePer1000: 1.6,
        minQuantity: 50,
        maxQuantity: 30000,
        speedLabel: "Instant",
        qualityScore: 8.2,
        retentionPercent: 82,
        refillDays: 0,
      },
    ],
  },
  {
    name: "LinkedIn",
    icon: "work",
    services: [
      {
        serviceType: "Followers",
        name: "LinkedIn Profile/Page Followers",
        description: "Grow your professional network or company Page with real profiles.",
        icon: "group",
        pricePer1000: 6.0,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "24 hours start",
        badge: "Elite",
        qualityScore: 9.2,
        retentionPercent: 91,
        refillDays: 30,
      },
      {
        serviceType: "Post Likes",
        name: "LinkedIn Post Likes",
        description: "Real professional-profile likes for posts and articles.",
        icon: "thumb_up",
        pricePer1000: 3.0,
        minQuantity: 50,
        maxQuantity: 20000,
        speedLabel: "Instant",
        qualityScore: 8.6,
        retentionPercent: 86,
        refillDays: 0,
      },
      {
        serviceType: "Post Comments",
        name: "LinkedIn Custom Comments",
        description: "Professional, context-aware comments written to match your post.",
        icon: "chat",
        pricePer1000: 9.0,
        minQuantity: 10,
        maxQuantity: 500,
        speedLabel: "12 hours start",
        badge: "Stable",
        qualityScore: 9.3,
        retentionPercent: 96,
        refillDays: 0,
      },
      {
        serviceType: "Connections",
        name: "LinkedIn Connection Requests Accepted",
        description: "Real professionals who accept your outreach connection requests.",
        icon: "person_add",
        pricePer1000: 15.0,
        minQuantity: 20,
        maxQuantity: 2000,
        speedLabel: "3-5 days",
        badge: "Elite",
        qualityScore: 9.0,
        retentionPercent: 88,
        refillDays: 0,
      },
    ],
  },
];

async function main() {
  for (const [index, category] of catalog.entries()) {
    const savedCategory = await prisma.serviceCategory.upsert({
      where: { name: category.name },
      update: { icon: category.icon, sortOrder: index },
      create: { name: category.name, icon: category.icon, sortOrder: index },
    });

    for (const service of category.services) {
      await prisma.service.upsert({
        where: {
          // No natural unique key beyond id, so key on name (unique enough
          // for a seed script — the real catalog will come from a supplier
          // API per PLANO.md section 6).
          id: `${savedCategory.id}-${service.serviceType}-${service.name}`
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, "-"),
        },
        update: {
          ...service,
          categoryId: savedCategory.id,
        },
        create: {
          id: `${savedCategory.id}-${service.serviceType}-${service.name}`
            .toLowerCase()
            .replace(/[^a-z0-9]+/g, "-"),
          categoryId: savedCategory.id,
          ...service,
        },
      });
    }

    console.log(`Seeded ${category.services.length} services for ${category.name}`);
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
